# Generated by Django 2.0.2 on 2018-02-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
