# Generated by Django 2.0.2 on 2018-02-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0002_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('avgSpeed', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('throttlePosition', models.IntegerField()),
            ],
        ),
    ]
